#!/usr/bin/env bash

NAME=bw

cat << EOF > /tmp/Dockerfile.${NAME}
FROM node:14-alpine
RUN npm install @bitwarden/cli -g
ENTRYPOINT [ "bw" ]
EOF

docker build -qt ${NAME} -f /tmp/Dockerfile.${NAME} ~/.dotfiles > /dev/null
docker run --rm --env-file <(env | grep BW) -v ~/.config:/root/.config -i ${NAME} $@
