#!/usr/bin/env bash

CRED_SEARCH_TERM=${1}
if [ -z ${CRED_SEARCH_TERM} ]; then
   printf "No search term provided \n" 1>&2
   exit 0;
fi
shift;

BW_INFO=$(bw list items | jq -r ".[] | select(.name == \"${CRED_SEARCH_TERM}\")")
USERNAME=$(echo $BW_INFO | jq -er '.login.username')
PASSWORD=$(echo $BW_INFO | jq -er '.login.password')

if [ $? -ne 0 ]; then
  printf "Unable to get username/password \n" 1>&2
  exit 0;
fi
USERNAME=$USERNAME PASSWORD=$PASSWORD eval "$@"
