#!/usr/bin/env bash

NAME=cf

cat << EOF > /tmp/Dockerfile.${NAME}
FROM node:14-alpine
RUN \
  apk -U upgrade -a && \
  apk update && \
  apk add git
RUN git clone https://github.com/danielpigott/cloudflare-cli.git /usr/src/app
WORKDIR /usr/src/app
RUN npm install
RUN npm link

ENTRYPOINT [ "cfcli" ]
EOF

docker build -q -t ${NAME} -f /tmp/Dockerfile.${NAME} ~/.dotfiles > /dev/null
docker run --rm --env-file <(env | grep CF) -it ${NAME} $@
