#!/usr/bin/env bash

NAME=gen_gitignore

cat << EOF > /tmp/Dockerfile.${NAME}
FROM node:14-alpine
RUN npm install --global generate generate-gitignore
CMD [ "sh", "-ic", "gen gitignore" ]
EOF

docker build -q -t ${NAME} -f /tmp/Dockerfile.${NAME} ~/.dotfiles > /dev/null
docker run --rm  -v $(pwd):/mnt -w /mnt -it ${NAME} $@
