#!/bin/bash

NAME=makefile2graph

cat << EOF > /tmp/Dockerfile.${NAME}
FROM alpine:3.12
RUN \
  apk add --no-cache graphviz make git gcc libc-dev && \
  rm -fr /var/cache/apk/*
ENV LANG en_US.UTF-8
RUN git clone --branch v1.5.0 https://github.com/lindenb/makefile2graph && \
    cd makefile2graph && \
    make
WORKDIR "/makefile2graph"
ENTRYPOINT ["./make2graph"]
EOF


docker build -q -t ${NAME} -f /tmp/Dockerfile.${NAME} ~/.dotfiles > /dev/null
cat - | docker run --rm -i ${NAME} $@
