#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

ffmpeg -hide_banner \
       -loglevel info \
       -thread_queue_size 512 \
       -f x11grab \
       $(xwininfo -id $(xdotool getwindowfocus) | gawk 'match($0, /-geometry ([0-9]+x[0-9]+).([0-9]+).([0-9]+)/, a)\
         { print "-video_size " a[1] " -i +" a[2] "," a[3] }') \
       -thread_queue_size 512 \
       -f v4l2 \
       -i "/dev/video0" \
       -f pulse \
       -ac 2 \
       -i default \
       -c:v libx264 \
       -crf 0 \
       -preset ultrafast \
       -filter_complex '[1:v]scale=160:120 [ovrl], [0:v][ovrl]overlay=(main_w-overlay_w)-10:(main_h-overlay_h)-10' \
       -threads 0 -y $1
